module.exports = {
  moduleFileExtensions: ['js', 'json', 'ts'],
  rootDir: 'src',
  testRegex: '.*\\.spec\\.ts$',
  transform: {
    '^.+\\.(t|j)s$': 'ts-jest',
  },
  collectCoverageFrom: [
    '**/*.(t|j)s',
    '!**/*.spec.ts',
    '!**/*.e2e-spec.ts',
    '!**/node_modules/**',
    '!**/dist/**',
    '!**/*.interface.ts',
    '!**/*.dto.ts',
    '!**/*.entity.ts',
    '!**/*.enum.ts',
    '!**/*.decorator.ts',
    '!**/*.filter.ts',
    '!**/*.interceptor.ts',
    '!**/*.middleware.ts',
    '!**/*.strategy.ts',
    '!**/*.module.ts',
    '!**/main.ts',
    '!**/data-source.ts',
    '!**/seed-data-source.ts',
    '!**/migrations/**',
    '!**/seeds/**',
    '!**/config/**',
    '!**/test-setup.ts',
  ],
  coverageDirectory: '../coverage',
  testEnvironment: 'node',
  coverageReporters: ['text', 'lcov', 'html'],
  coverageThreshold: {
    global: {
      branches: 85,
      functions: 85,
      lines: 85,
      statements: 85,
    },
  },
  setupFilesAfterEnv: ['<rootDir>/test-setup.ts'],
};