openapi: 3.0.0
info:
  title: Real Estate API
  description: API for property management system
  version: 1.0
  contact:
    email: dev@realestateapi.com

servers:
  - url: http://localhost:3000
    description: Local server
  - url: https://api.realestate.com/v1
    description: Production server

tags:
  - name: properties
    description: Property operations
  - name: listings
    description: Property listings
  - name: transactions
    description: Property transactions
  - name: auth
    description: Authentication

paths:
  /v1/properties:
    get:
      tags: [properties]
      summary: Get all properties
      parameters:
        - $ref: '#/components/parameters/page'
        - $ref: '#/components/parameters/limit'
      responses:
        200:
          description: List of properties
          content:
            application/json:
              schema:
                type: object
                properties:
                  data:
                    type: array
                    items:
                      $ref: '#/components/schemas/Property'

components:
  securitySchemes:
    JWT-auth:
      type: http
      scheme: bearer
      bearerFormat: JWT
    refresh-token:
      type: http
      scheme: bearer
      bearerFormat: JWT

  schemas:
    Property:
      type: object
      properties:
        id:
          type: string
          format: uuid
        address:
          type: string
        location:
          type: object
          properties:
            type:
              type: string
              enum: [Point]
            coordinates:
              type: array
              items:
                type: number
              minItems: 2
              maxItems: 2
        valuation:
          type: number
          format: float

  parameters:
    page:
      name: page
      in: query
      description: Page number
      required: false
      schema:
        type: integer
        default: 1
    limit:
      name: limit
      in: query
      description: Items per page
      required: false
      schema:
        type: integer
        default: 10
